forge "http://forge.puppetlabs.com"

mod 'puppetlabs/apt'
# ExecJS provider for rails asset compilation
mod 'puppetlabs/nodejs'
mod 'puppetlabs/ruby'
mod 'puppetlabs/stdlib'
mod 'example42/mongodb'
mod 'ploperations/rack', :git => 'git@github.com:puppetlabs-operations/puppet-rack.git'
mod 'ploperations/bundler'
mod 'ploperations/unicorn'
mod 'alup/rbenv'