forge "http://forge.puppetlabs.com"

mod 'puppetlabs/apt'
mod 'puppetlabs/vcsrepo'
# ExecJS provider for rails asset compilation
mod 'puppetlabs/nodejs'
mod 'puppetlabs/ruby'
mod 'puppetlabs/stdlib'
mod 'example42/mongodb'
mod 'ploperations/rack', :git => 'git://github.com/puppetlabs-operations/puppet-rack.git'
mod 'ploperations/bundler'
mod 'unicorn', :git => 'git://github.com/maxlinc/puppet-unicorn.git', :ref => 'rbenv_friendly'
mod 'alup/rbenv'
